web/yelpy/yelpy/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from search import views

admin.autodiscover()

urlpatterns = patterns('',


	url(r'^$', 'yelpy.views.index', name='home'),
	url(r'^yelpy/profile/', 'yelpy.views.profile', name='profile'),
	url(r'^yelpy/search2/', 'yelpy.views.search2', name='search2'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^searchstuff/', views.searchview),
	url(r'^search/', views.searchview),
    url(r'^searchthings/', views.searchthings),
	url(r'^automaticquery/', views.automaticQuerying),
    url(r'^yelpy/users$', 'yelpy.views.create_user'),
    url(r'^yelpy/logout$', 'yelpy.views.logout'),
)

web/yelpy/yelpy/models.py
from django.db import models
from django import forms
from django.forms import ModelForm
import json

class All(models.Model):
    # class Meta:
    #     select_on_save = True

    id = models.CharField(primary_key=True, max_length=235)
    #---food categories---
    chinese = models.BooleanField()
    indian = models.BooleanField()
    vietnamese = models.BooleanField()
    thai = models.BooleanField()
    western = models.BooleanField()

    #---sports categories---
    fitness = models.BooleanField()
    golf = models.BooleanField()
    football = models.BooleanField()
    swimming = models.BooleanField()
    fishing = models.BooleanField()

    #---shop categories---
    clothes = models.BooleanField()
    accessories = models.BooleanField()
    women = models.BooleanField()
    children = models.BooleanField()
    men = models.BooleanField()
    gifts = models.BooleanField()

    #---arts categories---
    gallery = models.BooleanField()
    cinema = models.BooleanField()
    theater = models.BooleanField()



    def __unicode__(self):
        return "sdss"

    @staticmethod
    def category_dict():
        return {
            'chinese': 'food',
            'indian': 'food',
            'vietnamese': 'food',
            'thai': 'food',
            'western': 'food',

            'fitness': 'sports',
            'golf': 'sports',
            'football': 'sports',
            'swimming': 'sports',
            'fishing': 'sports',

            'clothes': 'shops',
            'accessories': 'shops',
            'women': 'shops',
            'children': 'shops',
            'men': 'shops',
            'gifts': 'shops',

            'gallery': 'arts',
            'cinema': 'arts',
            'theater': 'arts',
        }

class User(models.Model):
    id = models.CharField(primary_key =True, max_length = 235)
    name = models.CharField(max_length = 255)

    # def __unicode__(self):
    #   return self.name

    def as_dict(self):
        return {
            'id': self.id,
            'name': self.name
        }

web/yelpy/yelpy/forms.py
from django.forms import ModelForm
from yelpy.models import All
from django import forms


class AllForm(ModelForm):
    class Meta:
        model = All
        fields = ['chinese', 'indian','vietnamese','thai','western','fitness','golf','football','swimming','fishing','clothes','accessories','women','children','men','gifts','gallery','cinema','theater','id']
        # exclude = ['id']
    def process(self):
        cd = self.cleaned_data
        print cd['chinese']
    def __init__(self, *args, **kwargs):
        super(AllForm, self).__init__(*args, **kwargs)
        self.fields['id'].widget = forms.HiddenInput()

web/yelpy/yelpy/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import *
from yelpy.forms import *
from django.views.decorators.csrf import csrf_exempt
from yelpy.models import User
from django.core import serializers
from django.forms.models import model_to_dict
import json
import logging

logger = logging.getLogger(__name__)

def index(request):
    return render(request, 'yelpy/index.html', {
        'fb_id': request.session.get('fb_user_id', '')
    })

@csrf_exempt
def profile(request):
    if request.method == 'POST':
        form = AllForm(data=request.POST)
        if form.is_valid():
            form.save()

        else:
            userId = request.POST.get('id', '')
            obj = All.objects.get(id=userId)

            obj.chinese = request.POST.get('chinese', '')
            obj.indian = request.POST.get('indian', '')
            obj.vietnamese = request.POST.get('vietnamese', '')
            obj.thai = request.POST.get('thai', '')
            obj.western= request.POST.get('western', '')
            obj.fitness = request.POST.get('fitness', '')
            obj.golf = request.POST.get('golf', '')
            obj.football = request.POST.get('football', '')
            obj.swimming = request.POST.get('swimming', '')
            obj.fishing = request.POST.get('fishing', '')
            obj.clothes = request.POST.get('clothes', '')
            obj.accessories = request.POST.get('accessories', '')
            obj.women = request.POST.get('women', '')
            obj.children = request.POST.get('children', '')
            obj.men = request.POST.get('men', '')
            obj.gifts = request.POST.get('gifts', '')
            obj.gallery = request.POST.get('gallery', '')
            obj.cinema = request.POST.get('cinema', '')
            obj.theater = request.POST.get('theater', '')
            messages.info(request, "Success! Check your personalised results at the <a href='/automaticquery/'>Search</a> page.")
            obj.save()

    else: # not a POST request
        userId = request.session.get('fb_user_id', '')
        user_prefs_data = None

        if userId:
            user_objects = All.objects.filter(id=userId)
            if len(user_objects):
                user_prefs_data = model_to_dict(user_objects[0])

        form = AllForm(data=user_prefs_data)

    return render(request, 'yelpy/profile.html', {
        'form': form,
        'fb_id': request.session.get('fb_user_id', '')
    })

def search2(request):
    return render(request,'yelpy/search2.html')

def form(request):
    if request.method == 'POST':
        form = AllForm(request.POST)
        if form.is_valid():
            chinese = form.cleaned_data['chinese']
            indian = form.cleaned_data['indian']
            vietnamese = form.cleaned_data['vietnamese']
            thai = form.cleaned_data['thai']
            western = form.cleaned_data['western']

            return render(request, 'yelpy/landing.html', {
                'chinese': chinese, 'indian':indian, 'vietnamese':vietnamese,'thai':thai,'western':western,
            })

    return render(request, 'yelpy/profile.html', {
        'form': form,
    })


@csrf_exempt
def create_user(request):
    if request.method == 'POST':
        id = request.POST.get('id', '')
        name = request.POST.get('name', '')
        users = User.objects.filter(id=id)

        session_fb_id = request.session.get('fb_user_id', '')

        if session_fb_id != id:
            request.session['fb_user_id'] = id

        if len(users) == 0: # User doesn't exist, create one
            user_object = User(id = id, name = name)
            user_object.save()
            # users = User.objects.filter(id=id)
            return HttpResponse(json.dumps("Created user and logged in."), content_type="application/json")

        return HttpResponse(json.dumps("Logged in."), content_type="application/json")

    # users = User.objects.all()
    return HttpResponse(json.dumps("Who should I log in?"), content_type="application/json")

def logout(request):
    fb_user_id = request.session.get('fb_user_id', '')
    if fb_user_id:
        request.session.flush()

    return HttpResponse(json.dumps("Logged out, if there was anyone logged in."), content_type="application/json")

web/yelpy/yelpy/templates/yelpy/_footer.html
      <footer class="footer">
        <p><i>Created by Chia Yan An, Kok Mun Kiat, Sahil Bajaj, and Shahbaaz Sabharwal</i></p>
      </footer>
    </div>

    <!-- Scripts -->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
    <!-- jQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>

    <!-- Facebook -->
    <script>
      var fbUserInfoDeferred = $.Deferred();

      window.fbAsyncInit = function() {
        FB.init({
          appId      : '218688974992726',
          status     : true,
          cookie     : true,
          xfbml      : true
        });

        FB.Event.subscribe('auth.login', function() {
          fbUserInfoDeferred = $.Deferred();

          FB.api('/me', function (response) {
            fbUserInfoDeferred.resolve(response);
          });

          displayFbUsername(true);
        });

        FB.Event.subscribe('auth.logout', function(response) {
          fbUserInfoDeferred = $.Deferred();
          fbUserInfoDeferred.reject(response);

          displayFbUsername();
        });

        FB.Event.subscribe('auth.authResponseChange', function(response) {

          fbUserInfoDeferred = $.Deferred();

          if (response.status === 'connected') {

            FB.api('/me', function (response) {
              fbUserInfoDeferred.resolve(response);
            });

          } else if (response.status === 'not_authorized') {
            FB.login();
            fbUserInfoDeferred.reject();
          } else {
            fbUserInfoDeferred.reject();
          }

          displayFbUsername();
        });
      };

      // Load the SDK asynchronously
      (function(d){
        var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        ref.parentNode.insertBefore(js, ref);
      }(document));

    </script>

    <script>
      function displayFbUsername(reload) {
        fbUserInfoDeferred.done(function (response) {
          $('.fb-username').html(response.first_name + ' ' + response.last_name);

          $.post('/yelpy/users', {
            'id': response.id,
            'name': response.first_name + ' ' + response.last_name
          }).done(function () {
            console.log('data posted');
            if (reload) {
              location.reload();
            }
          });

          $('#id_fb_id').val(response.id);
          $('#id_id').val(response.id);
        });

        fbUserInfoDeferred.fail(function () {
          $('.fb-username').html('');
          $('#id_fb_id').val('');
          $('#id_id').val('');

          $.get('/yelpy/logout').done(function () {
            console.log('Logged out');
            location.reload();
          })
        });

        return fbUserInfoDeferred.promise();
      }

      $(document).ready(function () {
        displayFbUsername();
      })
    </script>
  </body>
</html>

web/yelpy/yelpy/templates/yelpy/_header.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Yelpy — Your Personalised Yelp&trade; Search!</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">

    <!-- Latest compiled and minified JavaScript -->
  </head>
  <body>
      <div class="container">
      	<header class="header">
          <div class="pull-right header-fb-info">
            <small><span class="fb-username">&nbsp;</span></small>
            <fb:login-button class="fb-login-button" data-size="medium" data-auto-logout-link="true"></fb:login-button>
          </div>
          <ul class="nav nav-pills pull-right">
            <li><a href="/">Home</a></li>
            <li><a href="/yelpy/profile">Profile</a></li>
            <li><a href="/automaticquery">Search</a></li>
          </ul>
		      <h3 class="text-muted">Yelpy!</h3>
      	</header>

web/yelpy/yelpy/templates/yelpy/index.html
{% include 'yelpy/_header.html' %}
      <div class="jumbotron">
        <h1>Yelpy!</h1>
        <p class="lead">Your Personalised Yelp&trade; Search!</p>
      </div>
      <form>
        {% csrf_token %}
      </form>
      <p style='text-align:center'>
        {% if fb_id %}
           Update your search preferences in your <a href="/yelpy/profile">Profile</a>, and then go to the <a href="/automaticquery">Search</a> page to view results! The name Yelpy! originated to signify 'your' element of the application, through the extra 'y'. 
        {% else %}
          Please log in.
        {% endif %}
      </p>
{% include 'yelpy/_footer.html' %}

web/yelpy/yelpy/templates/yelpy/profile.html
{% load bootstrap3 %}
{% include 'yelpy/_header.html' %}
{% bootstrap_messages %}
  {% if fb_id %}
  <h1>Profile</h1>
  <p>Choose your preferences for the categories listed below to get your personalised results</p>
  <form method="POST">
    {% csrf_token %}
    {{ form.id }}
    <div class="row">
      {{ form.non_field_errors }}
      <div class="col-md-3">
        <h3>Food</h3>
        <div class="checkbox">
          <label>
            {{ form.chinese }} {{ form.chinese.errors }}
            {{ form.chinese.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.indian }}
            {{ form.indian.label}}
          </label>
        </div>
          <div class="checkbox">
          <label>
            {{ form.vietnamese }}
            {{ form.vietnamese.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.thai }}
            {{ form.thai.label}}
          </label>
        </div>
         <div class="checkbox">
          <label>
            {{ form.western }}
            {{ form.western.label}}
          </label>
        </div>
      </div>

      <div class="col-md-3">
        <h3>Sports</h3>
        <div class="checkbox">
          <label>
            {{ form.fitness }}
            {{ form.fitness.label}}
          </label>
        </div>
          <div class="checkbox">
          <label>
            {{ form.golf }}
            {{ form.golf.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.football }}
            {{ form.football.label}}
          </label>
        </div>
            <div class="checkbox">
          <label>
            {{ form.swimming }}
            {{ form.swimming.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.fishing }}
            {{ form.fishing.label}}
          </label>
        </div>
      </div>

      <div class="col-md-3">
        <h3>Shopping</h3>
        <div class="checkbox">
          <label>
            {{ form.clothes }}
            {{ form.clothes.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.accessories }}
            {{ form.accessories.label}}
          </label>
        </div>
         <div class="checkbox">
          <label>
            {{ form.women }}
            {{ form.women.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.children }}
            {{ form.children.label}}
          </label>
        </div>
          <div class="checkbox">
          <label>
            {{ form.men }}
            {{ form.men.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.gifts }}
            {{ form.gifts.label}}
          </label>
        </div>
      </div>

      <div class="col-md-3">
        <h3>Arts</h3>
        <div class="checkbox">
          <label>
            {{ form.gallery }}
            {{ form.gallery.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.cinema }}
            {{ form.cinema.label}}
          </label>
        </div>
        <div class="checkbox">
          <label>
            {{ form.theater }}
            {{ form.theater.label}}
          </label>
        </div>
      </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary">
    </div>
  </form>
  {% else %}
    <p>Please log in.</p>
  {% endif %}
{% include 'yelpy/_footer.html' %}